config:
  selfUrl: # https://saas.passwordlessauthentication.dev
  corsOrigins: https://passwordlessauthentication-st-gateway-web,https://passwordlessauthentication-st-gateway-public-web
  connectionStrings:
    administrationService: #
    saasService: #
  authServer:
    authority: # http://passwordlessauthentication-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.passwordlessauthentication.dev/.well-known/openid-configuration
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: saas.passwordlessauthentication.dev
  tlsSecret: passwordlessauthentication-tls

image:
  repository: mycompanyname/passwordlessauthentication-service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      