using PasswordlessAuthentication.ProductService.Products;

namespace PasswordlessAuthentication.ProductService.EntityFrameworkCore.Domains;

public class ProductServiceRepositoryTests : ProductServiceRepositoryTests<ProductServiceEntityFrameworkCoreTestModule>
{

}
