using PasswordlessAuthentication.ProductService.Products;

namespace PasswordlessAuthentication.ProductService.EntityFrameworkCore.Applications;

public class EfCoreProductAppServiceTests : ProductAppService_Tests<ProductServiceEntityFrameworkCoreTestModule>
{

}
